<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AstHelpers\AstHelpers.csproj" />
      <ProjectReference Include="..\ErrorHelper\ErrorHelper.csproj" />
      <ProjectReference Include="..\OLangAst\OLangAst.csproj" />
      <ProjectReference Include="..\OLangHelpers\OLangHelpers.csproj" />
    </ItemGroup>

</Project>
