<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>OLangCompiler</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="my_obj\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="OneOf" Version="3.0.271" />
    </ItemGroup>

</Project>
