<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>OLangCompiler</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="my_obj\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OLangHelpers\OLangHelpers.csproj" />
      <ProjectReference Include="..\OLangTokenizer\OLangTokenizer.csproj" />
    </ItemGroup>
</Project>
